name: install-pip-deps
description: "Install required Python dependencies"
inputs:
  repo-path:
    description: "Path to the Python app repository"
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - name: Install Python dependencies
      run: |
        echo "Installing all required Python dependencies..."
        pip install -r requirements.txt
      shell: cmd
      working-directory: ${{ inputs.repo-path }}
