  install-pip-deps:
    runs-on: [self-hosted, Windows]
    steps:
      - name: Checkout this pipeline repo
        uses: actions/checkout@v4  # lai piekļūtu .github/actions

      - name: Clone python-greetings repo
        uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: python-greetings  # <- šī būs working-directory

      - name: Install pip deps
        uses: ./.github/actions/install-deps
        working-directory: python-greetings
