 Pārstrādātā versija ar npx (ieteicams):
yaml
Копировать
Редактировать
name: Run tests on environment
description: Run JS tests using newman against target environment
inputs:
  env:
    description: Environment name (e.g. dev, staging, preprod, prod)
    required: true
  port:
    description: Port for this environment (e.g. 7001)
    required: true

runs:
  using: "composite"
  steps:
    - name: Echo testing environment
      run: echo Running tests for ${{ inputs.env }} on port ${{ inputs.port }}
      shell: cmd
      working-directory: js-framework

    - name: Install npm dependencies
      run: npm install
      shell: cmd
      working-directory: js-framework

    - name: Run Newman tests directly
      run: npx newman run greetings.postman_collection.json --env-var host=http://localhost:${{ inputs.port }}
      shell: cmd
      working-directory: js-framework

    - name: Confirm tests completed
      run: echo Tests for ${{ inputs.env }} completed!
      shell: cmd
      working-directory: js-framework
