name: Run tests on environment
description: Run JS tests using mocha against target environment
inputs:
  env:
    description: Environment name (e.g. dev, staging, preprod, prod)
    required: true

runs:
  using: "composite"
  steps:
    - name: Echo testing environment
      run: echo Running tests for ${{ inputs.env }}
      shell: cmd
      working-directory: js-framework

    - name: Install npm dependencies
      run: npm install
      shell: cmd
      working-directory: js-framework

    - name: Run tests with ENV for global.env
      run: |
        set ENV=greetings_${{ inputs.env }} && npx mocha tests/scenarios/greetings/*.js --reporter mochawesome --timeout 20000
      shell: cmd
      working-directory: js-framework
