name: Run tests on environment
description: Run Mocha tests against greetings service
inputs:
  env:
    description: Environment name (e.g. dev, staging, preprod, prod)
    required: true

runs:
  using: "composite"
  steps:
    - name: Echo testing environment
      run: echo Running tests for ${{ inputs.env }}
      shell: cmd
      working-directory: js-framework

    - name: Set global.env for config lookup
      run: echo global.env=greetings_${{ inputs.env }}>> %GITHUB_ENV%
      shell: cmd

    - name: Install npm dependencies
      run: npm install
      shell: cmd
      working-directory: js-framework

    - name: Run tests
      run: npm run greetings
      shell: cmd
      working-directory: js-framework

    - name: Confirm tests completed
      run: echo Tests for ${{ inputs.env }} completed!
      shell: cmd
      working-directory: js-framework
