name: Run tests on environment
description: Run JS tests using npm against target environment
inputs:
  env:
    description: Environment name (e.g. dev, staging, preprod, prod)
    required: true

runs:
  using: "composite"
  steps:
    - name: Echo testing environment
      run: echo Running tests for ${{ inputs.env }} environment
      shell: cmd

    - name: Install npm dependencies
      run: npm install
      shell: cmd

    - name: Run test command
      run: npm run greetings_${{ inputs.env }}
      shell: cmd

    - name: Confirm tests completed
      run: echo Tests for ${{ inputs.env }} completed!
      shell: cmd
