name: Run tests on environment
description: Run Mocha tests using environment config
inputs:
  env:
    description: Environment name (e.g. dev, staging, preprod, prod)
    required: true

runs:
  using: "composite"
  steps:
    - name: Echo test environment
      run: echo Running tests for ${{ inputs.env }}
      shell: cmd
      working-directory: js-framework

    - name: Write environment to set-env.js
      run: echo global.env="greetings_${{ inputs.env }}" > set-env.js
      shell: cmd
      working-directory: js-framework

    - name: Install dependencies
      run: npm install
      shell: cmd
      working-directory: js-framework

    - name: Run Mocha tests with required env
      run: node --require ./set-env.js ./node_modules/mocha/bin/mocha tests/scenarios/greetings/*.js --reporter mochawesome --timeout 20000
      shell: cmd
      working-directory: js-framework

    - name: Confirm test run
      run: echo Tests finished for ${{ inputs.env }}
      shell: cmd
      working-directory: js-framework
