name: Run Mocha Tests with Global Env
description: >
  Composite action to run Mocha tests with a global.env value 
  injected based on the input environment.
inputs:
  env:
    description: "Target environment (e.g. dev, staging, prod) to map into config key."
    required: true

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'  # Use Node.js 18 (LTS) for the runner

    - name: Install dependencies
      run: npm ci

    - name: Run Mocha tests
      shell: 'node {0}'
      run: |
        // Inject the global.env variable for the desired config key
        global.env = "greetings_${{ inputs.env }}";
        console.log(`Set global.env = "${global.env}"`);

        // Run the Mocha test suite (with Mochawesome reporter)
        require('child_process').execSync(
          'mocha tests/scenarios/greetings/*.js --reporter mochawesome',
          { stdio: 'inherit' }
        );
