name: Run tests on environment
description: Run JS tests against target environment
inputs:
  env:
    description: Environment name (e.g. dev, staging, preprod, prod)
    required: true

runs:
  using: "composite"
  steps:
    - name: Echo testing environment
      run: echo Running tests for ${{ inputs.env }}
      shell: cmd
      working-directory: js-framework

    - name: Install npm dependencies
      run: npm install
      shell: cmd
      working-directory: js-framework

    - name: Run mocha tests with injected env
      run: node -e "global.env='greetings_${{ inputs.env }}'; require('child_process').execSync('npx mocha tests/scenarios/greetings/*.js --reporter mochawesome --timeout 20000', { stdio: 'inherit' })"
      shell: cmd
      working-directory: js-framework
