name: Run tests on environment
description: Run JS tests against target environment
inputs:
  env:
    description: Environment name (e.g. dev, staging, preprod, prod)
    required: true

runs:
  using: "composite"
  steps:
    - name: Echo testing environment
      run: echo Running tests for ${{ inputs.env }}
      shell: cmd
      working-directory: js-framework

    - name: Set global.env
      run: Set-Content -Path set-env.js -Value 'global.env="greetings_${{ inputs.env }}"'
      shell: powershell
      working-directory: js-framework

    - name: Install npm dependencies
      run: npm install
      shell: cmd
      working-directory: js-framework

    - name: Run tests
      run: node --require ./set-env.js ./node_modules/mocha/bin/mocha tests/scenarios/greetings/*.js --reporter mochawesome --timeout 20000
      shell: cmd
      working-directory: js-framework

    - name: Confirm tests completed
      run: echo Tests for ${{ inputs.env }} completed!
      shell: cmd
      working-directory: js-framework
