name: Run tests on environment
description: Run JS tests using mocha and mochawesome, setting global.env dynamically

inputs:
  env:
    description: Environment name (e.g. dev, staging, preprod, prod)
    required: true

runs:
  using: "composite"
  steps:
    - name: Echo testing environment
      run: echo Running tests for ${{ inputs.env }}
      shell: cmd
      working-directory: js-framework

    - name: Install npm dependencies
      run: npm install
      shell: cmd
      working-directory: js-framework

    - name: Run Mocha tests with global.env
      shell: node
      working-directory: js-framework
      run: |
        // Set global.env so request.js can pick correct host
        global.env = "greetings_${{ inputs.env }}";
        console.log("Running tests with global.env =", global.env);

        const { execSync } = require("child_process");
        execSync("npx mocha tests/scenarios/greetings/*.js --reporter mochawesome --timeout 20000", {
          stdio: "inherit"
        });
