name: Run tests on environment
description: Run JS tests with mocha and mochawesome

inputs:
  env:
    description: Environment name (e.g. dev, staging, preprod, prod)
    required: true

runs:
  using: "composite"
  steps:
    - name: Echo testing environment
      run: echo Running tests for ${{ inputs.env }}
      shell: cmd
      working-directory: js-framework

    - name: Create set-env.js with global.env
      run: echo global.env=\"greetings_${{ inputs.env }}\" > set-env.js
      shell: cmd
      working-directory: js-framework

    - name: Install npm dependencies
      run: npm install
      shell: cmd
      working-directory: js-framework

    - name: Run Mocha tests with global.env
      run: node --require ./set-env.js ./node_modules/mocha/bin/mocha tests/scenarios/greetings/*.js --reporter mochawesome --timeout 20000
      shell: cmd
      working-directory: js-framework
