name: Deploy
description: Deploy Python app using PM2

inputs:
  env:
    description: Environment name (e.g., dev, staging)
    required: true
  port:
    description: Port number
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout pipeline repo (main repo)
      uses: actions/checkout@v4

    - name: Checkout python-greetings repo
      uses: actions/checkout@v4
      with:
        repository: mtararujs/python-greetings
        path: python-greetings

    - name: Force delete old python-greetings folder
      run: |
        IF EXIST python-greetings (
          rmdir /S /Q python-greetings
        )
      shell: cmd

    - name: Clone python-greetings repo again
      uses: actions/checkout@v4
      with:
        repository: mtararujs/python-greetings
        path: python-greetings

    - name: Stop existing PM2 service
      run: pm2 delete greetings-app-${{ inputs.env }} || exit 0
      shell: cmd

    - name: Start Python app with PM2
      run: pm2 start app.py --name greetings-app-${{ inputs.env }} -- --port ${{ inputs.port }} --no-debugger
      working-directory: python-greetings
      shell: cmd
