name: Deploy
description: Deploy Python app using PM2

inputs:
  env:
    description: Environment name (e.g., dev, staging)
    required: true
  port:
    description: Port number
    required: true

runs:
  using: "composite"
  steps:
    - name: Kill Python processes if running
      run: |
        taskkill /F /IM python.exe || echo "Python not running"
      shell: cmd

    - name: Force delete old python-greetings folder
      run: |
        IF EXIST python-greetings (
          rmdir /S /Q python-greetings
        )
      shell: cmd

    - name: Checkout python app
      uses: actions/checkout@v4
      with:
        repository: mtararujs/python-greetings
        path: python-greetings

    - name: Delete old PM2 process
      run: pm2 delete greetings-app-${{ inputs.env }} || exit 0
      shell: cmd

    - name: Start python app
      run: pm2 start app.py --name greetings-app-${{ inputs.env }} -- --port ${{ inputs.port }}
      working-directory: python-greetings
      shell: cmd
