name: "Deploy Python App"
description: "Deploy python app using pm2"
inputs:
  env:
    description: "Environment name (dev, stg, etc)"
    required: true
  port:
    description: "Port number"
    required: true

runs:
  using: "composite"
  steps:
    - name: Force delete old python-greetings folder
      run: |
        IF EXIST python-greetings (
          rmdir /S /Q python-greetings
        )
      shell: cmd

    - name: Checkout python app
      uses: actions/checkout@v4
      with:
        repository: mtararujs/python-greetings
        path: python-greetings

    - name: Stop Python if running
      run: |
        taskkill /F /IM python.exe || exit /B 0
      shell: cmd

    - name: Stop existing pm2 service (ignore error if not running)
      run: pm2 delete greetings-app-${{ inputs.env }} || exit /B 0
      shell: cmd

- name: Start new app with pm2
  run: pm2 start app.py --name greetings-app-${{ inputs.env }} --interpreter python -- --port ${{ inputs.port }} --no-debugger
  working-directory: python-greetings
  shell: cmd

- name: Wait for app to be ready
  run: timeout /t 3 > NUL
  shell: cmd
