name: Deploy Python App

description: Start Python app with PM2

inputs:
  env:
    description: Environment name (e.g. dev, staging, preprod, prod)
    required: true
  port:
    description: Port to run the app
    required: true

runs:
  using: "composite"
  steps:
    - name: Stop PM2 and Python if running
      shell: cmd
      run: |
        pm2 delete all || exit /B 0
        taskkill /F /IM python.exe || exit /B 0
        IF EXIST python-greetings (
          rmdir /S /Q python-greetings
        )

    - name: Checkout python app
      uses: actions/checkout@v4
      with:
        repository: mtararujs/python-greetings
        path: python-greetings

    - name: Start new app with pm2
      run: pm2 start app.py --name greetings-app-${{ inputs.env }} --interpreter python -- --port ${{ inputs.port }} --no-debugger
      working-directory: python-greetings
      shell: cmd

    - name: Wait for app to be ready
      shell: cmd
      run: timeout /t 3 /nobreak

