name: Deploy Python Greetings Service
description: "Use PM2 to (re)deploy the Python Greetings app to a given environment"
inputs:
  env:
    description: "Target environment name (dev, staging, preprod, prod)"
    required: true
  port:
    description: "Port number to run the service on"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout Python service repository
      uses: actions/checkout@v4
      with:
        repository: mtararujs/python-greetings
        path: python-greetings
    - name: Starting deployment
      run: echo "Deploying application to '${{ inputs.env }}' environment (port ${{ inputs.port }})..."
      shell: bash
    - name: Stop existing service (if running)
      run: pm2 delete greetings-app-${{ inputs.env }} || true
      shell: bash
      working-directory: python-greetings
    - name: Start service with PM2
      run: pm2 start app.py --name greetings-app-${{ inputs.env }} -- --port ${{ inputs.port }}
      shell: bash
      working-directory: python-greetings
