name: Deploy to environment
description: Stop existing app and start Python app with PM2
inputs:
  env:
    description: Environment name (e.g. dev, staging, preprod, prod)
    required: true
  port:
    description: Port number for this environment
    required: true

runs:
  using: "composite"
  steps:
    - name: Echo environment
      run: echo Deploying to ${{ inputs.env }} on port ${{ inputs.port }}
      shell: cmd
      working-directory: ./python-greetings

    - name: Stop existing PM2 process
      run: pm2 delete greetings-app-${{ inputs.env }} & EXIT /B 0
      shell: cmd
      working-directory: ./python-greetings

    - name: Start app using PM2
      run: pm2 start app.py --name greetings-app-${{ inputs.env }} -- --port ${{ inputs.port }}
      shell: cmd
      working-directory: ./python-greetings

    - name: Confirm deployment
      run: echo App deployed to ${{ inputs.env }} successfully!
      shell: cmd
      working-directory: ./python-greetings
