name: 'Deploy Python Greetings App (Windows)'
description: 'Deploys the Python Greetings application on a Windows runner using PM2.'

inputs:
  env:
    description: 'Deployment environment name (e.g., dev or staging)'
    required: true
    type: string
  port:
    description: 'Port number for the application (e.g., 7001)'
    required: true
    type: string

runs:
  using: 'composite'
  steps:
    - name: Stop existing app processes
      shell: cmd
      run: |
        echo Stopping any existing PM2 service named greetings-app-${{ inputs.env }} and any running Python processes...
        pm2 stop "greetings-app-${{ inputs.env }}" || exit /B 0
        pm2 delete "greetings-app-${{ inputs.env }}" || exit /B 0
        taskkill /F /IM python.exe /T || exit /B 0

    - name: Remove old application folder
      shell: cmd
      run: |
        echo Deleting old 'python-greetings' folder if it exists...
        IF EXIST "python-greetings" RMDIR /S /Q "python-greetings"

    - name: Clone repository
      shell: cmd
      run: |
        echo Cloning the python-greetings repository...
        git clone https://github.com/mtararujs/python-greetings "python-greetings"

    - name: Start application with PM2
      shell: cmd
      run: |
        echo Starting the application with PM2 on port ${{ inputs.port }}...
        cd "python-greetings"
        pm2 start app.py --name "greetings-app-${{ inputs.env }}" --interpreter python -- --port ${{ inputs.port }} --no-debugger

    - name: Wait for app startup
      shell: cmd
      run: |
        echo Pausing for 3 seconds to allow the app to fully start...
        timeout /T 3 /NOBREAK > NUL
