name: Python Greetings CI/CD

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  install-pip-deps:
    runs-on: self-hosted
    steps:
      - name: Checkout pipeline repo
        uses: actions/checkout@v4

      - name: Force delete old python-greetings folder
        run: |
          taskkill /F /IM python.exe || exit 0
          IF EXIST python-greetings (
            rmdir /S /Q python-greetings
          )
        shell: cmd

      - name: Checkout python app
        uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: python-greetings

      - name: Install Python dependencies
        run: pip install -r requirements.txt
        working-directory: python-greetings
        shell: cmd

  deploy-to-dev:
    runs-on: self-hosted
    needs: install-pip-deps
    steps:
      - name: Checkout pipeline repo
        uses: actions/checkout@v4

      - name: Force delete old python-greetings folder
        run: |
          taskkill /F /IM python.exe || exit 0
          IF EXIST python-greetings (
            rmdir /S /Q python-greetings
          )
        shell: cmd

      - name: Checkout python app
        uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: python-greetings

      - name: Delete old pm2 service
        run: pm2 delete greetings-app-dev || exit 0
        shell: cmd

      - name: Start app with pm2
        run: pm2 start app.py --name greetings-app-dev -- --port 7001
        working-directory: python-greetings
        shell: cmd
