name: Python Greetings CI/CD Pipeline
on:
  workflow_dispatch: {}  # Manual trigger

jobs:
  install-pip-deps:
    runs-on: [self-hosted, Windows]
    steps:
      - name: Checkout pipeline repository
        uses: actions/checkout@v4

      - name: Clone python-greetings repo
        uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: python-greetings

      - name: Install Python dependencies
        uses: ./.github/actions/install-deps
        working-directory: python-greetings

  deploy-to-dev:
    needs: install-pip-deps
    runs-on: [self-hosted, Windows]
    steps:
      - name: Checkout pipeline repo
        uses: actions/checkout@v4

      - name: Clone python-greetings repo
        uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: python-greetings

      - name: Deploy to Dev
        uses: ./.github/actions/deploy-env
        with:
          env: dev
          port: 7001
        working-directory: python-greetings

  tests-on-dev:
    needs: deploy-to-dev
    runs-on: [self-hosted, Windows]
    steps:
      - name: Checkout pipeline repo
        uses: actions/checkout@v4

      - name: Clone test framework
        uses: actions/checkout@v4
        with:
          repository: mtararujs/course-js-api-framework
          path: js-framework

      - name: Run tests on Dev
        uses: ./.github/actions/test-env
        with:
          env: dev
        working-directory: js-framework

  deploy-to-staging:
    needs: tests-on-dev
    runs-on: [self-hosted, Windows]
    steps:
      - name: Checkout pipeline repo
        uses: actions/checkout@v4

      - name: Clone python-greetings repo
        uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: python-greetings

      - name: Deploy to Staging
        uses: ./.github/actions/deploy-env
        with:
          env: staging
          port: 7002
        working-directory: python-greetings

  tests-on-staging:
    needs: deploy-to-staging
    runs-on: [self-hosted, Windows]
    steps:
      - name: Checkout pipeline repo
        uses: actions/checkout@v4

      - name: Clone test framework
        uses: actions/checkout@v4
        with:
          repository: mtararujs/course-js-api-framework
          path: js-framework

      - name: Run tests on Staging
        uses: ./.github/actions/test-env
        with:
          env: staging
        working-directory: js-framework

  deploy-to-preprod:
    needs: tests-on-staging
    runs-on: [self-hosted, Windows]
    steps:
      - name: Checkout pipeline repo
        uses: actions/checkout@v4

      - name: Clone python-greetings repo
        uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: python-greetings

      - name: Deploy to Preprod
        uses: ./.github/actions/deploy-env
        with:
          env: preprod
          port: 7003
        working-directory: python-greetings

  tests-on-preprod:
    needs: deploy-to-preprod
    runs-on: [self-hosted, Windows]
    steps:
      - name: Checkout pipeline repo
        uses: actions/checkout@v4

      - name: Clone test framework
        uses: actions/checkout@v4
        with:
          repository: mtararujs/course-js-api-framework
          path: js-framework

      - name: Run tests on Preprod
        uses: ./.github/actions/test-env
        with:
          env: preprod
        working-directory: js-framework

  deploy-to-prod:
    needs: tests-on-preprod
    runs-on: [self-hosted, Windows]
    steps:
      - name: Checkout pipeline repo
        uses: actions/checkout@v4

      - name: Clone python-greetings repo
        uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: python-greetings

      - name: Deploy to Prod
        uses: ./.github/actions/deploy-env
        with:
          env: prod
          port: 7004
        working-directory: python-greetings

  tests-on-prod:
    needs: deploy-to-prod
    runs-on: [self-hosted, Windows]
    steps:
      - name: Checkout pipeline repo
        uses: actions/checkout@v4

      - name: Clone test framework
        uses: actions/checkout@v4
        with:
          repository: mtararujs/course-js-api-framework
          path: js-framework

      - name: Run tests on Prod
        uses: ./.github/actions/test-env
        with:
          env: prod
        working-directory: js-framework
