name: Python Greetings CI/CD
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  install-pip-deps:
    runs-on: [self-hosted]
    steps:
      # Ensure pipeline repo is checked out (access to .github/actions)
      - uses: actions/checkout@v4
      - name: Install Python dependencies
        uses: ./.github/actions/install-pip-deps

  deploy-to-dev:
    runs-on: [self-hosted]
    needs: install-pip-deps  # run only after dependencies are installed
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Dev
        uses: ./.github/actions/deploy
        with:
          env: dev
          port: 7001

  tests-on-dev:
    runs-on: [self-hosted]
    needs: deploy-to-dev  # run only after Dev deployment is complete
    steps:
      - uses: actions/checkout@v4
      - name: Test on Dev
        uses: ./.github/actions/test
        with:
          env: dev
          port: 7001

  deploy-to-staging:
    runs-on: [self-hosted]
    needs: tests-on-dev
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Staging
        uses: ./.github/actions/deploy
        with:
          env: staging
          port: 7002

  tests-on-staging:
    runs-on: [self-hosted]
    needs: deploy-to-staging
    steps:
      - uses: actions/checkout@v4
      - name: Test on Staging
        uses: ./.github/actions/test
        with:
          env: staging
          port: 7002

  deploy-to-preprod:
    runs-on: [self-hosted]
    needs: tests-on-staging
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Preprod
        uses: ./.github/actions/deploy
        with:
          env: preprod
          port: 7003

  tests-on-preprod:
    runs-on: [self-hosted]
    needs: deploy-to-preprod
    steps:
      - uses: actions/checkout@v4
      - name: Test on Preprod
        uses: ./.github/actions/test
        with:
          env: preprod
          port: 7003

  deploy-to-prod:
    runs-on: [self-hosted]
    needs: tests-on-preprod
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Prod
        uses: ./.github/actions/deploy
        with:
          env: prod
          port: 7004

  tests-on-prod:
    runs-on: [self-hosted]
    needs: deploy-to-prod
    steps:
      - uses: actions/checkout@v4
      - name: Test on Prod
        uses: ./.github/actions/test
        with:
          env: prod
          port: 7004
